name: Debug On Comment
on:
  issue_comment:
    types: [created]
jobs:
  debug:
    name: Event
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: |
          echo "${{github.event.comment.author_association}}"